location="northeurope"
tfstate_rg_name="elasticsearch_demo_tfstate_rg"
tfstate_storage_account_name="elasticsearchdemosa"
tfstate_container_name="elasticsearch-demo-tfstate-c"
tfstate_key="elasticsearch.tfstate"