version: '3.8'

services:

  gateway:
    container_name: Gateway
    image: envoyproxy/envoy:v1.20.2
    ports:
      - "8001:8001"
      - "8000:8000"
    volumes:
      - ../../src/Gateway/envoy.yml:/etc/envoy/envoy.yaml
    depends_on:
    - demo-api
    - elasticsearch
    - kibana

  demo-api:
    container_name: DemoApi
    image: elasticsearch_demo/demo-api:latest
    build:
      context: ../../
      dockerfile: src/Demo.Api/Dockerfile
    ports:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
    - elasticsearch

  elasticsearch:
    container_name: ElasticSearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    environment:
    - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
    - "9200:9200"
    
  kibana:
    container_name: Kibana
    image: docker.elastic.co/kibana/kibana:8.1.0
    ports:
    - "5601:5601"
    environment:
    - SERVERNAME=kibana
    - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
    - ELASTICSEARCH_USERNAME=kibana_system
    - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
    - elasticsearch